# Generated by Django 2.1.15 on 2020-08-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesoresfisiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='urlGoogleScholar',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
